/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qdict;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import java.io.*;
import com.sun.speech.freetts.*;
import javax.swing.JEditorPane;

/**
 *
 * @author Quy
 */
public class MainFrame extends javax.swing.JFrame {
    private ReadData dataEv;
    private ReadData dataVe;
    private ReadData dataAddedEv;
    private ReadData dataAddedVe;
    private int SeLan = 1;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setResizable(false);
        this.setLocation(500, 50);
//        JMenuBar menuBar = new JMenuBar();
//        add(menuBar);
//        JMenu file = new JMenu("File");
//        file.setMnemonic(KeyEvent.VK_F);
//        menuBar.add(file);
//        JMenu edit = new JMenu("Edit");
//        edit.setMnemonic(KeyEvent.VK_E);
        
        try {
            dataEv = new ReadData("data/E_V.txt");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            dataVe = new ReadData("data/V_E.txt");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            dataAddedEv = new ReadData("data/addedE_V.txt");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            dataAddedVe = new ReadData("data/addedV_E.txt");
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        tfWord = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btSearch = new javax.swing.JButton();
        lbMean = new javax.swing.JLabel();
        cbSeLan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btSpeak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMean = new javax.swing.JTextPane();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Từ điển QDict");
        setPreferredSize(new java.awt.Dimension(480, 600));

        jLabel2.setText("Từ cần tra");

        btSearch.setText("Tra nghĩa");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        lbMean.setText("Nghĩa của từ");

        cbSeLan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En->Vi", "Vi->En" }));
        cbSeLan.setToolTipText("Select Language");
        cbSeLan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSeLanItemStateChanged(evt);
            }
        });

        jLabel4.setText("<html><b><font color=\"green\">Welcome to QDict</font></b></html>");

        btSpeak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qdict/images/speaker.png"))); // NOI18N
        btSpeak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSpeakActionPerformed(evt);
            }
        });

        txtMean.setEditable(false);
        txtMean.setContentType("text/html"); // NOI18N
        jScrollPane1.setViewportView(txtMean);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSearch)
                    .addComponent(tfWord, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSpeak, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSeLan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbMean))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSeLan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btSpeak, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btSearch)
                .addGap(11, 11, 11)
                .addComponent(lbMean)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btSpeak, cbSeLan, tfWord});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        String word = tfWord.getText();
        lbMean.setText("<html>Nghĩa của từ <b><i color='green'>" + word + "</i></b> : </html>");
        if(1 == SeLan){
            
            try {
                word = Std.StdStrE(word);
                txtMean.setText(dataEv.searchMean(word));
            } catch (NullPointerException e) {
                try {
                    txtMean.setText(dataAddedEv.searchMean(word));
                } catch (NullPointerException e1) {
                    txtMean.setText("<html><i color='red'>Không có từ cần tìm kiếm</i></html>");
                } 
            }
        }else{
            word = Std.StdStrV(word);
            try {
                txtMean.setText(dataVe.searchMean(word));
            } catch (NullPointerException e) {
                try {
                    txtMean.setText(dataAddedVe.searchMean(word));
                } catch (Exception e1) {
                    txtMean.setText("<html><i color='red'>Không có từ cần tìm kiếm</i></html>");
                }
            }
        }        
    }//GEN-LAST:event_btSearchActionPerformed

    private void cbSeLanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSeLanItemStateChanged
        // TODO add your handling code here:
        if("En->Vi".equals(cbSeLan.getSelectedItem().toString())){
            SeLan = 1;
        }
        else{
            SeLan = 2;
        }
    }//GEN-LAST:event_cbSeLanItemStateChanged

    private void btSpeakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSpeakActionPerformed
        Speak.voice(tfWord.getText());
    }//GEN-LAST:event_btSpeakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btSpeak;
    private javax.swing.JComboBox<String> cbSeLan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMean;
    private javax.swing.JTextField tfWord;
    private javax.swing.JTextPane txtMean;
    // End of variables declaration//GEN-END:variables
}
